project:
  type: website
  output-dir: docs
  
format:
  html:
    theme: solar
website:
  title: "R-Hisp"
  site-url: https://rhisp.github.io/Rhisp_web
  description: "Pruebas nueva web"
  page-navigation: true
  navbar:
    search: true
    background: light
    collapse-below: lg
    type: light
    logo: "img/logo_cabecera.png"
    right:

      - icon: twitter
        href: https://twitter.com/R_Hisp
      - text: Resources
        menu: 
          - text: Web R-es.org actual
            href: http://r-es.org
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/ 
  sidebar: 
    background: "#D9E3E4"
    pinned: true
    align: center
    contents: 
     - href: quienes-somos.qmd
       text: ¿QUIÉNES SOMOS? 
    
            

filters:
  - lightbox

lightbox: auto
#########################  
  
editor: source
