project:
  type: website
  output-dir: docs
  
highlight-style: ayu
code-annotations: hover

website:
  page-navigation: true
  title: "Comunidad R Hispano"
  description: "Asociación de usuarios de R de España"
  site-url: "https://rhisp.github.io/Rhisp_web/"
  repo-url: https://github.com/rhisp/Rhisp_web
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@R_Hisp"
    image: "images/logo_twitter.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "Comunidad RHispano"
  
  navbar:
    background: "#F9F6F6"
    logo: "images/logo_hexagonal.jpeg"
    tools: 
      - icon: github
        href: https://github.com/rhisp
      - icon: twitter
        href: https://twitter.com/R_Hisp
        
    left:
      - text: QUIÉNES SOMOS
        href: quienes-somos.qmd 
      - text: HAZTE SOCIO/A
        href: hazte_socia.qmd 
      - text: JORNADAS
        href: Jornadas_post.qmd
      - sidebar:empleo
      - sidebar:formacion
      - text: GRUPOS LOCALES
        href: grupos-locales.qmd
      - text: BLOG
        href: blog.qmd

  sidebar:
    - id: ""
    - id: empleo
      title: "EMPLEO"
      style: "docked"
      collapse-level: 2
      contents:
        - empleo.qmd
        - section: Post empleo
          contents:
            - auto: empleo_post/**/*.qmd
    - id: formacion
      title: "FORMACION"
      style: "docked"
      collapse-level: 2
      contents:
       - auto: formacion_post/*.qmd
format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


freeze: auto

editor: visual

filters:
  - lightbox
